services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./docker/backend/Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: true

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./docker/frontend/Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: true

  - type: private_service
    name: postgres
    env: docker
    dockerfilePath: ./docker/db/Dockerfile
    dockerContext: .
    plan: free
