# Generated by Django 5.1.3 on 2025-03-02 14:56

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('birth_date', models.DateField()),
                ('snils', models.CharField(max_length=11, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('registration_address', models.CharField(max_length=500)),
                ('actual_address', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='faces/')),
                ('face_vector', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
            ],
            options={
                'ordering': ['snils'],
                'indexes': [models.Index(fields=['snils'], name='patient_pat_snils_406302_idx')],
            },
        ),
    ]
