# Generated by Django 5.1.3 on 2025-03-08 21:36

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['snils'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='actual_address',
            field=models.CharField(help_text='Фактический адрес проживания пациента', max_length=500, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(help_text='Дата рождения пациента', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='face_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, help_text='Векторное представление лица пациента', null=True, verbose_name='Вектор лица'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(help_text='Имя пациента', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Пол пациента', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(help_text='Фамилия пациента', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text='Отчество пациента (не обязательно)', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(help_text='Фотография пациента для распознавания', upload_to='faces/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_address',
            field=models.CharField(help_text='Адрес регистрации пациента', max_length=500, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='snils',
            field=models.CharField(help_text='Уникальный СНИЛС пациента', max_length=11, unique=True, verbose_name='СНИЛС'),
        ),
    ]
