# Generated by Django 5.1.3 on 2025-03-15 23:08

import apps.patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(help_text='Дата рождения пациента', validators=[apps.patient.models.validate_birth_date], verbose_name='Дата рождения'),
        ),
    ]
