# Generated by Django 5.1.3 on 2025-03-02 14:56

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', help_text='Отчество (не обязательно)', max_length=100, verbose_name='Отчество')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Уникальный телефон формата +7**********', max_length=128, region='RU', unique=True)),
                ('hospital', models.ForeignKey(blank=True, help_text='Мед учереждение, к которому прикреплен сотрудник', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='medical_hub.hospital', verbose_name='Мед учереждение')),
                ('specialization', models.ManyToManyField(help_text='Специализации лечащего врача', related_name='doctors_specializations', to='medical_hub.specialty', verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', help_text='Отчество (не обязательно)', max_length=100, verbose_name='Отчество')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Уникальный телефон формата +7**********', max_length=128, region='RU', unique=True)),
                ('hospital', models.ForeignKey(blank=True, help_text='Мед учереждение, к которому прикреплен сотрудник', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrars', to='medical_hub.hospital', verbose_name='Мед учереждение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Регистратура',
                'verbose_name_plural': 'Регистратура',
            },
        ),
    ]
