# Generated by Django 5.1.3 on 2025-03-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('form', models.CharField(choices=[('таблетки', 'Таблетки'), ('капсулы', 'Капсулы'), ('сипроп', 'Сироп'), ('аэрозоль', 'Аэрозоль'), ('инъекции', 'Инъекции')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
