# Generated by Django 5.1.3 on 2025-03-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_medical_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Заболевание', 'verbose_name_plural': 'Заболевания'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Препарат', 'verbose_name_plural': 'Препараты'},
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Подробное описание заболевания', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(help_text='Уникальное название заболевания', max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Подробное описание препарата', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='form',
            field=models.CharField(choices=[('таблетки', 'Таблетки'), ('капсулы', 'Капсулы'), ('сироп', 'Сироп'), ('аэрозоль', 'Аэрозоль'), ('инъекции', 'Инъекции')], help_text='Форма выпуска препарата', max_length=20, verbose_name='Форма выпуска'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(help_text='Уникальное название препарата', max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['name'], name='catalog_med_name_dd2c81_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['name'], name='catalog_med_name_a9a851_idx'),
        ),
    ]
