# Generated by Django 5.1.3 on 2025-03-08 21:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(help_text='Адрес больницы', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Электронная почта больницы', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(help_text='Название больницы', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Уникальный телефон больницы', max_length=128, region='RU', unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание специализации', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(help_text='Название специализации', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
