# Generated by Django 5.1.3 on 2025-03-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_medical_data', '0002_alter_disease_options_alter_medication_options_and_more'),
        ('med_personal', '0002_alter_doctor_first_name_alter_doctor_hospital_and_more'),
        ('medical_card', '0001_initial'),
        ('medical_hub', '0002_alter_hospital_address_alter_hospital_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicalcardentry',
            name='check_diagnosis_required',
        ),
        migrations.RemoveConstraint(
            model_name='medicalcardentry',
            name='check_single_diagnosis_required',
        ),
        migrations.AddConstraint(
            model_name='medicalcardentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('diagnosis__isnull', False), ('custom_diagnosis__isnull', False)), models.Q(('diagnosis__isnull', True), ('custom_diagnosis__isnull', True)), _connector='OR'), name='check_one_diagnosis_required'),
        ),
    ]
