# Generated by Django 5.1.3 on 2025-03-11 15:10

import django.core.validators
from django.db import migrations, models
from apps.medical_card.utils import medical_card_entry_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0002_remove_medicalcardentry_check_diagnosis_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcardentryfile',
            name='file',
            field=models.FileField(help_text='Файл, прикрепленный к записи медкарты', upload_to=medical_card_entry_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Файл медзаписи'),
        ),
    ]
