# Generated by Django 5.1.3 on 2025-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_medical_data', '0002_alter_disease_options_alter_medication_options_and_more'),
        ('medical_card', '0004_remove_medicalcardentry_check_one_diagnosis_required_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['medical_card_entry'], name='medical_car_medical_0b8773_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionmedication',
            index=models.Index(fields=['prescription'], name='medical_car_prescri_24e143_idx'),
        ),
    ]
