# Generated by Django 5.1.3 on 2025-03-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_medical_data', '0002_alter_disease_options_alter_medication_options_and_more'),
        ('med_personal', '0002_alter_doctor_first_name_alter_doctor_hospital_and_more'),
        ('medical_card', '0005_prescription_medical_car_medical_0b8773_idx_and_more'),
        ('medical_hub', '0002_alter_hospital_address_alter_hospital_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicalcardentry',
            name='check_one_diagnosis_required',
        ),
        migrations.AddConstraint(
            model_name='medicalcardentry',
            constraint=models.CheckConstraint(condition=models.Q(('diagnosis__isnull', True), ('custom_diagnosis__isnull', True), _connector='OR'), name='check_one_diagnosis_only'),
        ),
        migrations.AddConstraint(
            model_name='medicalcardentry',
            constraint=models.CheckConstraint(condition=models.Q(('diagnosis__isnull', False), ('custom_diagnosis__isnull', False), _connector='OR'), name='check_one_diagnosis_required'),
        ),
    ]
