# Generated by Django 5.1.3 on 2025-03-15 23:08

from apps import medical_card
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0007_remove_medicalcardentry_check_one_diagnosis_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcardentry',
            name='visit_date',
            field=models.DateField(help_text='Фактическая дата приема пациента', validators=[
                medical_card.models.validate_visit_date], verbose_name='Дата визита'),
        ),
    ]
