# Generated by Django 5.1.3 on 2025-04-10 18:33

import apps.medical_card.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0008_alter_medicalcardentry_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcardentryfile',
            name='file',
            field=models.FileField(help_text='Файл, прикрепленный к записи медкарты', max_length=500, upload_to=apps.medical_card.utils.medical_card_entry_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Файл медзаписи'),
        ),
    ]
